### ISSUE TITLE
encoding videos stopped working

### ISSUE THREAD

**Issue by digitalkram** [codevise/pageflow-embedded-video#11]
hi

encoding videos stopped working for us all of the sudden. put to s3 is flagged as success but encoding is marked as failed after it reached 100%. Zencoder logs show success and the encoding results are available in S3 but in the editor it is marked as failed. In the DB there is encoding_error=null => not helpful.

I noticed that thumbnail-0.jpg and poster-0.jpg are missing however. Maybe that is the issue? Creating the thumbnails? Is this done locally? While I didn't update pageflow itself I had some platform updates...

I can see nothing relevant in the logs? Or maybe I look in the wrong place...
EDIT: I found this in log/jobs/env/resizing.log:
exception for Pageflow::VideoFile 45: Errno::ETIMEDOUT: Connection timed out - connect(2)

Question woudl be what the destination of this connection attempt is? Can verbosity be increased?
Any pointer is highly appreciated. thanks!

P.s.: media-gfx/imagemagick 6.9.0.3 is installed (but no update since it stopped working)

**Comment by tf** [comment]
Hi,

sorry for the late response. Please open issues regarding video encoding in the [codevise/pageflow](https://github.com/codevise/pageflow) repository. `pageflow-embedded-video` is only about YouTube/Vimeo embeds.

After Zencoder processing is done, the `PollZencoderJob` tries [to download thumbnail and poster images](https://github.com/codevise/pageflow/blob/master/app/jobs/pageflow/poll_zencoder_job.rb#L44) from the S3 bucket. If, as you noted, these files are missing in the S3 bucket, this could result in an error. I would not expect it to be a "connection timed out" error though. Can you double check your S3 configuration for video files (in particular the `s3_host_alias` in `config.zencoder_options`). Maybe also output `video_file.zencoder_thumbnail.url` via the console for one of the affected files and try to open the URL inside the browser.

At the moment there is no way to increase log verbosity. It would probably be great if there were `logger.debug` calls inside [`PollZencoderJob`](https://github.com/codevise/pageflow/blob/master/app/jobs/pageflow/poll_zencoder_job.rb) that output some of the API calls and requested URLs. Happy to accept a PR here.

**Comment by tf** [comment]
Feel free to open an issue in codevise/pageflow if the problem persists.

**Comment by digitalkram** [comment]
thx tf, will do - in july after my vacation
