### ISSUE TITLE
Translations Not Found

### ISSUE THREAD

**Issue by Sunbeam03** [codevise/pageflow-embedded-video#3]
Embedded Video fields all lack the english translation.

en.yml file exists and all configurations have been set as specified in the readme.

pageflow (0.8.1)
pageflow-embedded-video (0.1.0)

![image](https://cloud.githubusercontent.com/assets/13367338/8802295/7e1dc2e8-2f8e-11e5-95cd-b20b8ffbb356.png)

**Comment by tf** [comment]
Have you tried [this fix from the trouble shooting wiki page](https://github.com/codevise/pageflow/wiki/Troubleshooting#missing-translations-in-editor)?

**Comment by Sunbeam03** [comment]
I had not. Thank you for pointing that out I completely missed it when I was looking through the troubleshooting.
